config/routes.rb
Rails.application.routes.draw do

  resources :questions
  root 'questions#question1'

  get '/question1', to: "questions#question1"

  get '/question2', to: "questions#question2"

  get '/question3', to: "questions#question3"

  get '/question4', to: "questions#question4"

  get '/question5', to: "questions#question5"

  get '/question6', to: "questions#question6"

  get '/question7', to: "questions#question7"

  get '/question8', to: "questions#question8"

  get '/results', to: "questions#results"

  post '/answer', to: "questions#answer"

  get 'static_pages/home'
  get 'static_pages/help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :set_quiz

  def question1
    @question = @random[0]
  end

  def question2
    @question = @random[1]

  end

  def question3
    @question = @random[2]
  end

  def question4
    @question = @random[3]
  end

  def question5
    @question = @random[4]
  end

  def question6
    @question = @random[5]

  end

  def question7
    @question = @random[6]
  end

  def question8
    @question = @random[7]
  end

  def results
    session[:attempts] ||=[]

    @correct = 0;
    @total = session[:answered].length()
    @questionsanswered = session[:answered]

    @questionsanswered.each do |check|
      if check[1].eql?(true)
        @correct += 1
      end
    end

    time = Time.now.strftime("%H:%M %d-%m-%Y")
    session[:attempts].push([time, @correct, @total])

  end

  def answer
    if validanswer(params)
      session[:answered] ||= []
      numberofquestions ||= numberasked

      @question = Question.all.find_by(:question_id => params[:qid])
      @answer = params[:singleAnswer]

      if(@answer.eql?("answer_a") && @question.answer_a_correct.eql?("true"))
        result = true
      elsif(@answer.eql?("answer_b") && @question.answer_b_correct.eql?("true"))
        result = true
      elsif(@answer.eql?("answer_c") && @question.answer_c_correct.eql?("true"))
        result = true
      elsif(@answer.eql?("answer_d") && @question.answer_d_correct.eql?("true"))
        result = true
      elsif(@answer.eql?("answer_e") && @question.answer_e_correct.eql?("true"))
        result = true
      elsif(@answer.eql?("answer_f") && @question.answer_f_correct.eql?("true"))
        result = true
      else
        result = false
      end

      session[:answered].push([params[:qid], result])

      if(session[:answered].length() == 1)
        redirect_to '/question2'
      elsif(session[:answered].length() == 2)
        redirect_to '/question3'
      elsif(session[:answered].length() == 3)
        redirect_to '/question4'
      elsif(session[:answered].length() == 4 && session[:answered].length() < numberasked)
        redirect_to '/question5'
      elsif(session[:answered].length() == 5 && session[:answered].length() < numberasked)
        redirect_to '/question6'
      elsif(session[:answered].length() == 6 && session[:answered].length() < numberasked)
        redirect_to '/question7'
      elsif(session[:answered].length() == 7 && session[:answered].length() < numberasked)
        redirect_to '/question8'
      else
        numberofquestions = 0;
        redirect_to '/results'
      end
    end
  end

  def validanswer(params)
    params.has_key?(:singleAnswer)
  end

  def numberasked
    return rand(4..8)
  end

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:question_id)
    end

    def set_quiz
      @random = Question.all.shuffle
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
 <div>
   <h4 class="mb-3">Completed Credit level</h4>

  <a href="https://www.facebook.com/">Facebook</a>
  <a href="https://au.linkedin.com/">LinkedIn</a>
  <a href="https://twitter.com/home?lang=en">Twitter</a>

 </div>
</footer>

app/views/layouts/_header.html.erb
<% @page_title = yield(:html_title) %>
<header>
    <h1 class="mb-3">Christopher Tauro</h1>
    <h4 class="mb-3">s3788064@student.rmit.edu.au</h4>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>

</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.text_field :question_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @random.each do |question| %>
      <tr>
        <td><%= question.question_id %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/question1.html.erb
<p>
  <h1>Question:</h1>
  <%= @question.question %>

  <form href="/answer">
    <div class="form-check" action="/question2">
      <% if (@question[:answer_a] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_a" value="answer_a">
        <%= @question[:answer_a] %>
      <% end %><br>
      <% if (@question[:answer_b] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_b" value="answer_b">
        <%= @question[:answer_b] %>
      <% end %><br>
      <% if (@question[:answer_c] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_c" value="answer_c">
        <%= @question[:answer_c] %>
      <% end %><br>
      <% if (@question[:answer_d] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_d" value="answer_d">
        <%= @question[:answer_d] %>
      <% end %><br>
      <% if (@question[:answer_e] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_e" value="answer_e">
        <%= @question[:answer_e] %>
      <% end %><br>
      <% if (@question[:answer_f] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_f" value="answer_f">
        <%= @question[:answer_f] %>
      <% end %><br>
    </div>
    <button type="submit" class="btn btn-primary" >Submit</button>
</form>
</p>

app/views/questions/question2.html.erb
<p>
  <h1>Question 2:</h1>
  <%= @question.question %>

  <%= form_tag '/answer' do |form| %>
  <%= hidden_field_tag 'qid', @question.question_id %>
  <%= hidden_field_tag '', @question.question_id %>
    <div class="form-check" action="/question2">
      <% if (@question[:answer_a] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_a" value="answer_a">
        <%= @question[:answer_a] %>
      <% end %><br>
      <% if (@question[:answer_b] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_b" value="answer_b">
        <%= @question[:answer_b] %>
      <% end %><br>
      <% if (@question[:answer_c] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_c" value="answer_c">
        <%= @question[:answer_c] %>
      <% end %><br>
      <% if (@question[:answer_d] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_d" value="answer_d">
        <%= @question[:answer_d] %>
      <% end %><br>
      <% if (@question[:answer_e] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_e" value="answer_e">
        <%= @question[:answer_e] %>
      <% end %><br>
      <% if (@question[:answer_f] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_f" value="answer_f">
        <%= @question[:answer_f] %>
      <% end %><br>
    </div>
    <button type="submit" class="btn btn-primary" >Submit</button>
<% end %>
</p>

app/views/questions/question3.html.erb
<p>
  <h1>Question 3:</h1>
  <%= @question.question %>

  <%= form_tag '/answer' do |form| %>
  <%= hidden_field_tag 'qid', @question.question_id %>
  <%= hidden_field_tag '', @question.question_id %>
    <div class="form-check" action="/question2">
      <% if (@question[:answer_a] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_a" value="answer_a">
        <%= @question[:answer_a] %>
      <% end %><br>
      <% if (@question[:answer_b] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_b" value="answer_b">
        <%= @question[:answer_b] %>
      <% end %><br>
      <% if (@question[:answer_c] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_c" value="answer_c">
        <%= @question[:answer_c] %>
      <% end %><br>
      <% if (@question[:answer_d] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_d" value="answer_d">
        <%= @question[:answer_d] %>
      <% end %><br>
      <% if (@question[:answer_e] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_e" value="answer_e">
        <%= @question[:answer_e] %>
      <% end %><br>
      <% if (@question[:answer_f] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_f" value="answer_f">
        <%= @question[:answer_f] %>
      <% end %><br>
    </div>
    <button type="submit" class="btn btn-primary" >Submit</button>
<% end %>
</p>

app/views/questions/question4.html.erb
<p>
  <h1>Question 4:</h1>
  <%= @question.question %>

  <%= form_tag '/answer' do |form| %>
  <%= hidden_field_tag 'qid', @question.question_id %>
  <%= hidden_field_tag '', @question.question_id %>
    <div class="form-check" action="/question2">
      <% if (@question[:answer_a] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_a" value="answer_a">
        <%= @question[:answer_a] %>
      <% end %><br>
      <% if (@question[:answer_b] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_b" value="answer_b">
        <%= @question[:answer_b] %>
      <% end %><br>
      <% if (@question[:answer_c] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_c" value="answer_c">
        <%= @question[:answer_c] %>
      <% end %><br>
      <% if (@question[:answer_d] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_d" value="answer_d">
        <%= @question[:answer_d] %>
      <% end %><br>
      <% if (@question[:answer_e] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_e" value="answer_e">
        <%= @question[:answer_e] %>
      <% end %><br>
      <% if (@question[:answer_f] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_f" value="answer_f">
        <%= @question[:answer_f] %>
      <% end %><br>
    </div>
    <button type="submit" class="btn btn-primary" >Submit</button>
<% end %>
</p>

app/views/questions/question5.html.erb
<p>
  <h1>Question 5:</h1>
  <%= @question.question %>

  <%= form_tag '/answer' do |form| %>
  <%= hidden_field_tag 'qid', @question.question_id %>
  <%= hidden_field_tag '', @question.question_id %>
    <div class="form-check" action="/question2">
      <% if (@question[:answer_a] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_a" value="answer_a">
        <%= @question[:answer_a] %>
      <% end %><br>
      <% if (@question[:answer_b] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_b" value="answer_b">
        <%= @question[:answer_b] %>
      <% end %><br>
      <% if (@question[:answer_c] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_c" value="answer_c">
        <%= @question[:answer_c] %>
      <% end %><br>
      <% if (@question[:answer_d] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_d" value="answer_d">
        <%= @question[:answer_d] %>
      <% end %><br>
      <% if (@question[:answer_e] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_e" value="answer_e">
        <%= @question[:answer_e] %>
      <% end %><br>
      <% if (@question[:answer_f] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_f" value="answer_f">
        <%= @question[:answer_f] %>
      <% end %><br>
    </div>
    <button type="submit" class="btn btn-primary" >Submit</button>
<% end %>
</p>

app/views/questions/question6.html.erb
<p>
  <h1>Question 6:</h1>
  <%= @question.question %>

  <%= form_tag '/answer' do |form| %>
  <%= hidden_field_tag 'qid', @question.question_id %>
  <%= hidden_field_tag '', @question.question_id %>
    <div class="form-check" action="/question2">
      <% if (@question[:answer_a] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_a" value="answer_a">
        <%= @question[:answer_a] %>
      <% end %><br>
      <% if (@question[:answer_b] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_b" value="answer_b">
        <%= @question[:answer_b] %>
      <% end %><br>
      <% if (@question[:answer_c] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_c" value="answer_c">
        <%= @question[:answer_c] %>
      <% end %><br>
      <% if (@question[:answer_d] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_d" value="answer_d">
        <%= @question[:answer_d] %>
      <% end %><br>
      <% if (@question[:answer_e] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_e" value="answer_e">
        <%= @question[:answer_e] %>
      <% end %><br>
      <% if (@question[:answer_f] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_f" value="answer_f">
        <%= @question[:answer_f] %>
      <% end %><br>
    </div>
    <button type="submit" class="btn btn-primary" >Submit</button>
<% end %>
</p>

app/views/questions/question7.html.erb
<p>
  <h1>Question 7:</h1>
  <%= @question.question %>

  <%= form_tag '/answer' do |form| %>
  <%= hidden_field_tag 'qid', @question.question_id %>
  <%= hidden_field_tag '', @question.question_id %>
    <div class="form-check" action="/question2">
      <% if (@question[:answer_a] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_a" value="answer_a">
        <%= @question[:answer_a] %>
      <% end %><br>
      <% if (@question[:answer_b] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_b" value="answer_b">
        <%= @question[:answer_b] %>
      <% end %><br>
      <% if (@question[:answer_c] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_c" value="answer_c">
        <%= @question[:answer_c] %>
      <% end %><br>
      <% if (@question[:answer_d] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_d" value="answer_d">
        <%= @question[:answer_d] %>
      <% end %><br>
      <% if (@question[:answer_e] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_e" value="answer_e">
        <%= @question[:answer_e] %>
      <% end %><br>
      <% if (@question[:answer_f] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_f" value="answer_f">
        <%= @question[:answer_f] %>
      <% end %><br>
    </div>
    <button type="submit" class="btn btn-primary" >Submit</button>
<% end %>
</p>

app/views/questions/question8.html.erb
<p>
  <h1>Question 8:</h1>
  <%= @question.question %>

  <%= form_tag '/answer' do |form| %>
  <%= hidden_field_tag 'qid', @question.question_id %>
  <%= hidden_field_tag '', @question.question_id %>
    <div class="form-check" action="/question2">
      <% if (@question[:answer_a] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_a" value="answer_a">
        <%= @question[:answer_a] %>
      <% end %><br>
      <% if (@question[:answer_b] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_b" value="answer_b">
        <%= @question[:answer_b] %>
      <% end %><br>
      <% if (@question[:answer_c] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_c" value="answer_c">
        <%= @question[:answer_c] %>
      <% end %><br>
      <% if (@question[:answer_d] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_d" value="answer_d">
        <%= @question[:answer_d] %>
      <% end %><br>
      <% if (@question[:answer_e] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_e" value="answer_e">
        <%= @question[:answer_e] %>
      <% end %><br>
      <% if (@question[:answer_f] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_f" value="answer_f">
        <%= @question[:answer_f] %>
      <% end %><br>
    </div>
    <button type="submit" class="btn btn-primary" >Submit</button>
<% end %>
</p>

app/views/questions/results.html.erb
<p>
  <h1>Results:</h1><br>

  You scored: <%= @correct %>/<%= @total %>
  <br>

  <% @a = session[:attempts] %>
  <% @a.each do |a| %>
    On <%= a[0] %> you scored <%=a[1]%>/<%=a[2]%>.<br>
  <% end %>
  <%= link_to 'Go Again?', '/question1'%>
</p>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>

  <% if @question[:multiple_correct_answers].eql?("true")%>
    <div class="form-check">
      <% if (@question[:answer_a] != nil) %>
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <%= @question[:answer_a] %>
      <% end %><br>
      <% if (@question[:answer_b] != nil) %>
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck2">
        <%= @question[:answer_b] %>
      <% end %><br>
      <% if (@question[:answer_c] != nil) %>
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck3">
        <%= @question[:answer_c] %>
      <% end %><br>
      <% if (@question[:answer_d] != nil) %>
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck4">
        <%= @question[:answer_d] %>
      <% end %><br>
      <% if (@question[:answer_e] != nil) %>
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck5">
        <%= @question[:answer_e] %>
      <% end %><br>
      <% if (@question[:answer_f] != nil) %>
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck6">
        <%= @question[:answer_f] %>
      <% end %><br>
    </div>

  <% else %>
    <div class="form-check">
      <% if (@question[:answer_a] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_a" value="answer_a">
        <%= @question[:answer_a] %>
      <% end %><br>
      <% if (@question[:answer_b] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_b" value="answer_b">
        <%= @question[:answer_b] %>
      <% end %><br>
      <% if (@question[:answer_c] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_c" value="answer_c">
        <%= @question[:answer_c] %>
      <% end %><br>
      <% if (@question[:answer_d] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_d" value="answer_d">
        <%= @question[:answer_d] %>
      <% end %><br>
      <% if (@question[:answer_e] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_e" value="answer_e">
        <%= @question[:answer_e] %>
      <% end %><br>
      <% if (@question[:answer_f] != nil) %>
      <input class="form-check-input" type="radio" name="singleAnswer" id="radio_f" value="answer_f">
        <%= @question[:answer_f] %>
      <% end %><br>
    </div>
  <% end %>
</p>
<button type="submit" class="btn btn-primary">Submit</button>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>quiz#question1</h1>
<p>This is the first question</p>